name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

      # Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          sudo pip install aws-sam-cli

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Build with SAM
      - name: SAM Build
        run: sam build

      # # Package the application
      # - name: SAM Package
      #   run: |
      #     sam package \
      #       --s3-bucket ${{ secrets.S3_BUCKET }} \
      #       --output-template-file packaged.yaml

      # Deploy the application
      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name my-lambda-stack \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
